import type { Metadata } from "next";
import { Inter, Playfair_Display, Raleway } from "next/font/google";
import "./globals.css";
import AppLayout from "@/components/AppLayout";

const raleway = Raleway({ subsets: ["latin"]});
const playfairDisplay = Playfair_Display({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.className} ${playfairDisplay}`}>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
